<?php


/**
 * This class adds structure of 'plugin' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Dec 10 11:43:04 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PluginMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PluginMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PluginPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PluginPeer::TABLE_NAME);
		$tMap->setPhpName('Plugin');
		$tMap->setClassname('Plugin');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('AUTHOR_ID', 'AuthorId', 'INTEGER', 'author', 'ID', false, null);

		$tMap->addForeignKey('CATEGORY_ID', 'CategoryId', 'INTEGER', 'term', 'ID', false, null);

		$tMap->addForeignKey('STABLE_TAG_ID', 'StableTagId', 'INTEGER', 'plugin_tag', 'ID', false, null);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', false, 255);

		$tMap->addColumn('SLUG', 'Slug', 'VARCHAR', false, 255);

		$tMap->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null);

		$tMap->addColumn('DESCRIPTION_CLEAN', 'DescriptionClean', 'LONGVARCHAR', false, null);

		$tMap->addColumn('OFFICIAL', 'Official', 'BOOLEAN', false, null);

		$tMap->addColumn('DOCSURL', 'Docsurl', 'VARCHAR', false, 255);

		$tMap->addColumn('DEMOURL', 'Demourl', 'VARCHAR', false, 255);

		$tMap->addColumn('GITHUBUSER', 'Githubuser', 'VARCHAR', false, 100);

		$tMap->addColumn('GITHUBREPO', 'Githubrepo', 'VARCHAR', false, 100);

		$tMap->addColumn('HOWTOUSE', 'Howtouse', 'LONGVARCHAR', false, null);

		$tMap->addColumn('COMMENTS_COUNT', 'CommentsCount', 'INTEGER', false, null);

		$tMap->addColumn('DOWNLOADS_COUNT', 'DownloadsCount', 'INTEGER', false, null);

		$tMap->addColumn('RETRIEVED_AT', 'RetrievedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // PluginMapBuilder
