<?php

/**
 * Base class that represents a row from the 'author' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Dec 10 11:43:04 2009
 *
 * @package    lib.model.om
 */
abstract class BaseAuthor extends BaseObject  implements Persistent {


  const PEER = 'AuthorPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AuthorPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the username field.
	 * @var        string
	 */
	protected $username;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * The value for the fullname field.
	 * @var        string
	 */
	protected $fullname;

	/**
	 * The value for the location field.
	 * @var        string
	 */
	protected $location;

	/**
	 * The value for the homepageurl field.
	 * @var        string
	 */
	protected $homepageurl;

	/**
	 * The value for the about field.
	 * @var        string
	 */
	protected $about;

	/**
	 * The value for the avatar field.
	 * @var        string
	 */
	protected $avatar;

	/**
	 * The value for the twitter_id field.
	 * @var        string
	 */
	protected $twitter_id;

	/**
	 * The value for the checkhash field.
	 * @var        string
	 */
	protected $checkhash;

	/**
	 * The value for the plugins_count field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $plugins_count;

	/**
	 * The value for the confirmed_email field.
	 * @var        boolean
	 */
	protected $confirmed_email;

	/**
	 * The value for the admin field.
	 * @var        boolean
	 */
	protected $admin;

	/**
	 * The value for the logged_at field.
	 * @var        string
	 */
	protected $logged_at;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        array Plugin[] Collection to store aggregation of Plugin objects.
	 */
	protected $collPlugins;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPlugins.
	 */
	private $lastPluginCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseAuthor object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->plugins_count = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [username] column value.
	 * 
	 * @return     string
	 */
	public function getUsername()
	{
		return $this->username;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Get the [fullname] column value.
	 * 
	 * @return     string
	 */
	public function getFullname()
	{
		return $this->fullname;
	}

	/**
	 * Get the [location] column value.
	 * 
	 * @return     string
	 */
	public function getLocation()
	{
		return $this->location;
	}

	/**
	 * Get the [homepageurl] column value.
	 * 
	 * @return     string
	 */
	public function getHomepageurl()
	{
		return $this->homepageurl;
	}

	/**
	 * Get the [about] column value.
	 * 
	 * @return     string
	 */
	public function getAbout()
	{
		return $this->about;
	}

	/**
	 * Get the [avatar] column value.
	 * 
	 * @return     string
	 */
	public function getAvatar()
	{
		return $this->avatar;
	}

	/**
	 * Get the [twitter_id] column value.
	 * 
	 * @return     string
	 */
	public function getTwitterId()
	{
		return $this->twitter_id;
	}

	/**
	 * Get the [checkhash] column value.
	 * 
	 * @return     string
	 */
	public function getCheckhash()
	{
		return $this->checkhash;
	}

	/**
	 * Get the [plugins_count] column value.
	 * 
	 * @return     int
	 */
	public function getPluginsCount()
	{
		return $this->plugins_count;
	}

	/**
	 * Get the [confirmed_email] column value.
	 * 
	 * @return     boolean
	 */
	public function getConfirmedEmail()
	{
		return $this->confirmed_email;
	}

	/**
	 * Get the [admin] column value.
	 * 
	 * @return     boolean
	 */
	public function getAdmin()
	{
		return $this->admin;
	}

	/**
	 * Get the [optionally formatted] temporal [logged_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getLoggedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->logged_at === null) {
			return null;
		}


		if ($this->logged_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->logged_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->logged_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AuthorPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [username] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setUsername($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->username !== $v) {
			$this->username = $v;
			$this->modifiedColumns[] = AuthorPeer::USERNAME;
		}

		return $this;
	} // setUsername()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = AuthorPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = AuthorPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Set the value of [fullname] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setFullname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fullname !== $v) {
			$this->fullname = $v;
			$this->modifiedColumns[] = AuthorPeer::FULLNAME;
		}

		return $this;
	} // setFullname()

	/**
	 * Set the value of [location] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setLocation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->location !== $v) {
			$this->location = $v;
			$this->modifiedColumns[] = AuthorPeer::LOCATION;
		}

		return $this;
	} // setLocation()

	/**
	 * Set the value of [homepageurl] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setHomepageurl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->homepageurl !== $v) {
			$this->homepageurl = $v;
			$this->modifiedColumns[] = AuthorPeer::HOMEPAGEURL;
		}

		return $this;
	} // setHomepageurl()

	/**
	 * Set the value of [about] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setAbout($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->about !== $v) {
			$this->about = $v;
			$this->modifiedColumns[] = AuthorPeer::ABOUT;
		}

		return $this;
	} // setAbout()

	/**
	 * Set the value of [avatar] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setAvatar($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->avatar !== $v) {
			$this->avatar = $v;
			$this->modifiedColumns[] = AuthorPeer::AVATAR;
		}

		return $this;
	} // setAvatar()

	/**
	 * Set the value of [twitter_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setTwitterId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->twitter_id !== $v) {
			$this->twitter_id = $v;
			$this->modifiedColumns[] = AuthorPeer::TWITTER_ID;
		}

		return $this;
	} // setTwitterId()

	/**
	 * Set the value of [checkhash] column.
	 * 
	 * @param      string $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setCheckhash($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->checkhash !== $v) {
			$this->checkhash = $v;
			$this->modifiedColumns[] = AuthorPeer::CHECKHASH;
		}

		return $this;
	} // setCheckhash()

	/**
	 * Set the value of [plugins_count] column.
	 * 
	 * @param      int $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setPluginsCount($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->plugins_count !== $v || $v === 0) {
			$this->plugins_count = $v;
			$this->modifiedColumns[] = AuthorPeer::PLUGINS_COUNT;
		}

		return $this;
	} // setPluginsCount()

	/**
	 * Set the value of [confirmed_email] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setConfirmedEmail($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->confirmed_email !== $v) {
			$this->confirmed_email = $v;
			$this->modifiedColumns[] = AuthorPeer::CONFIRMED_EMAIL;
		}

		return $this;
	} // setConfirmedEmail()

	/**
	 * Set the value of [admin] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Author The current object (for fluent API support)
	 */
	public function setAdmin($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->admin !== $v) {
			$this->admin = $v;
			$this->modifiedColumns[] = AuthorPeer::ADMIN;
		}

		return $this;
	} // setAdmin()

	/**
	 * Sets the value of [logged_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Author The current object (for fluent API support)
	 */
	public function setLoggedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->logged_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->logged_at !== null && $tmpDt = new DateTime($this->logged_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->logged_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AuthorPeer::LOGGED_AT;
			}
		} // if either are not null

		return $this;
	} // setLoggedAt()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Author The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AuthorPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(AuthorPeer::PLUGINS_COUNT))) {
				return false;
			}

			if ($this->plugins_count !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->username = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->email = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->password = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->fullname = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->location = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->homepageurl = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->about = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->avatar = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->twitter_id = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->checkhash = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->plugins_count = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->confirmed_email = ($row[$startcol + 12] !== null) ? (boolean) $row[$startcol + 12] : null;
			$this->admin = ($row[$startcol + 13] !== null) ? (boolean) $row[$startcol + 13] : null;
			$this->logged_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->created_at = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = AuthorPeer::NUM_COLUMNS - AuthorPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Author object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AuthorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AuthorPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collPlugins = null;
			$this->lastPluginCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAuthor:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AuthorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			AuthorPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseAuthor:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAuthor:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(AuthorPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AuthorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseAuthor:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			AuthorPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AuthorPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AuthorPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AuthorPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPlugins !== null) {
				foreach ($this->collPlugins as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = AuthorPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPlugins !== null) {
					foreach ($this->collPlugins as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AuthorPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUsername();
				break;
			case 2:
				return $this->getEmail();
				break;
			case 3:
				return $this->getPassword();
				break;
			case 4:
				return $this->getFullname();
				break;
			case 5:
				return $this->getLocation();
				break;
			case 6:
				return $this->getHomepageurl();
				break;
			case 7:
				return $this->getAbout();
				break;
			case 8:
				return $this->getAvatar();
				break;
			case 9:
				return $this->getTwitterId();
				break;
			case 10:
				return $this->getCheckhash();
				break;
			case 11:
				return $this->getPluginsCount();
				break;
			case 12:
				return $this->getConfirmedEmail();
				break;
			case 13:
				return $this->getAdmin();
				break;
			case 14:
				return $this->getLoggedAt();
				break;
			case 15:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AuthorPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUsername(),
			$keys[2] => $this->getEmail(),
			$keys[3] => $this->getPassword(),
			$keys[4] => $this->getFullname(),
			$keys[5] => $this->getLocation(),
			$keys[6] => $this->getHomepageurl(),
			$keys[7] => $this->getAbout(),
			$keys[8] => $this->getAvatar(),
			$keys[9] => $this->getTwitterId(),
			$keys[10] => $this->getCheckhash(),
			$keys[11] => $this->getPluginsCount(),
			$keys[12] => $this->getConfirmedEmail(),
			$keys[13] => $this->getAdmin(),
			$keys[14] => $this->getLoggedAt(),
			$keys[15] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AuthorPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUsername($value);
				break;
			case 2:
				$this->setEmail($value);
				break;
			case 3:
				$this->setPassword($value);
				break;
			case 4:
				$this->setFullname($value);
				break;
			case 5:
				$this->setLocation($value);
				break;
			case 6:
				$this->setHomepageurl($value);
				break;
			case 7:
				$this->setAbout($value);
				break;
			case 8:
				$this->setAvatar($value);
				break;
			case 9:
				$this->setTwitterId($value);
				break;
			case 10:
				$this->setCheckhash($value);
				break;
			case 11:
				$this->setPluginsCount($value);
				break;
			case 12:
				$this->setConfirmedEmail($value);
				break;
			case 13:
				$this->setAdmin($value);
				break;
			case 14:
				$this->setLoggedAt($value);
				break;
			case 15:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AuthorPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUsername($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setEmail($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPassword($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFullname($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setLocation($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setHomepageurl($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setAbout($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setAvatar($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setTwitterId($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCheckhash($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setPluginsCount($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setConfirmedEmail($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setAdmin($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setLoggedAt($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setCreatedAt($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AuthorPeer::DATABASE_NAME);

		if ($this->isColumnModified(AuthorPeer::ID)) $criteria->add(AuthorPeer::ID, $this->id);
		if ($this->isColumnModified(AuthorPeer::USERNAME)) $criteria->add(AuthorPeer::USERNAME, $this->username);
		if ($this->isColumnModified(AuthorPeer::EMAIL)) $criteria->add(AuthorPeer::EMAIL, $this->email);
		if ($this->isColumnModified(AuthorPeer::PASSWORD)) $criteria->add(AuthorPeer::PASSWORD, $this->password);
		if ($this->isColumnModified(AuthorPeer::FULLNAME)) $criteria->add(AuthorPeer::FULLNAME, $this->fullname);
		if ($this->isColumnModified(AuthorPeer::LOCATION)) $criteria->add(AuthorPeer::LOCATION, $this->location);
		if ($this->isColumnModified(AuthorPeer::HOMEPAGEURL)) $criteria->add(AuthorPeer::HOMEPAGEURL, $this->homepageurl);
		if ($this->isColumnModified(AuthorPeer::ABOUT)) $criteria->add(AuthorPeer::ABOUT, $this->about);
		if ($this->isColumnModified(AuthorPeer::AVATAR)) $criteria->add(AuthorPeer::AVATAR, $this->avatar);
		if ($this->isColumnModified(AuthorPeer::TWITTER_ID)) $criteria->add(AuthorPeer::TWITTER_ID, $this->twitter_id);
		if ($this->isColumnModified(AuthorPeer::CHECKHASH)) $criteria->add(AuthorPeer::CHECKHASH, $this->checkhash);
		if ($this->isColumnModified(AuthorPeer::PLUGINS_COUNT)) $criteria->add(AuthorPeer::PLUGINS_COUNT, $this->plugins_count);
		if ($this->isColumnModified(AuthorPeer::CONFIRMED_EMAIL)) $criteria->add(AuthorPeer::CONFIRMED_EMAIL, $this->confirmed_email);
		if ($this->isColumnModified(AuthorPeer::ADMIN)) $criteria->add(AuthorPeer::ADMIN, $this->admin);
		if ($this->isColumnModified(AuthorPeer::LOGGED_AT)) $criteria->add(AuthorPeer::LOGGED_AT, $this->logged_at);
		if ($this->isColumnModified(AuthorPeer::CREATED_AT)) $criteria->add(AuthorPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AuthorPeer::DATABASE_NAME);

		$criteria->add(AuthorPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Author (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUsername($this->username);

		$copyObj->setEmail($this->email);

		$copyObj->setPassword($this->password);

		$copyObj->setFullname($this->fullname);

		$copyObj->setLocation($this->location);

		$copyObj->setHomepageurl($this->homepageurl);

		$copyObj->setAbout($this->about);

		$copyObj->setAvatar($this->avatar);

		$copyObj->setTwitterId($this->twitter_id);

		$copyObj->setCheckhash($this->checkhash);

		$copyObj->setPluginsCount($this->plugins_count);

		$copyObj->setConfirmedEmail($this->confirmed_email);

		$copyObj->setAdmin($this->admin);

		$copyObj->setLoggedAt($this->logged_at);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPlugins() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPlugin($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Author Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AuthorPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AuthorPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collPlugins collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPlugins()
	 */
	public function clearPlugins()
	{
		$this->collPlugins = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPlugins collection (array).
	 *
	 * By default this just sets the collPlugins collection to an empty array (like clearcollPlugins());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPlugins()
	{
		$this->collPlugins = array();
	}

	/**
	 * Gets an array of Plugin objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Author has previously been saved, it will retrieve
	 * related Plugins from storage. If this Author is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Plugin[]
	 * @throws     PropelException
	 */
	public function getPlugins($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AuthorPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlugins === null) {
			if ($this->isNew()) {
			   $this->collPlugins = array();
			} else {

				$criteria->add(PluginPeer::AUTHOR_ID, $this->id);

				PluginPeer::addSelectColumns($criteria);
				$this->collPlugins = PluginPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PluginPeer::AUTHOR_ID, $this->id);

				PluginPeer::addSelectColumns($criteria);
				if (!isset($this->lastPluginCriteria) || !$this->lastPluginCriteria->equals($criteria)) {
					$this->collPlugins = PluginPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPluginCriteria = $criteria;
		return $this->collPlugins;
	}

	/**
	 * Returns the number of related Plugin objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Plugin objects.
	 * @throws     PropelException
	 */
	public function countPlugins(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AuthorPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPlugins === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PluginPeer::AUTHOR_ID, $this->id);

				$count = PluginPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PluginPeer::AUTHOR_ID, $this->id);

				if (!isset($this->lastPluginCriteria) || !$this->lastPluginCriteria->equals($criteria)) {
					$count = PluginPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPlugins);
				}
			} else {
				$count = count($this->collPlugins);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Plugin object to this object
	 * through the Plugin foreign key attribute.
	 *
	 * @param      Plugin $l Plugin
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPlugin(Plugin $l)
	{
		if ($this->collPlugins === null) {
			$this->initPlugins();
		}
		if (!in_array($l, $this->collPlugins, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPlugins, $l);
			$l->setAuthor($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Author is new, it will return
	 * an empty collection; or if this Author has previously
	 * been saved, it will retrieve related Plugins from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Author.
	 */
	public function getPluginsJoinTerm($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AuthorPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlugins === null) {
			if ($this->isNew()) {
				$this->collPlugins = array();
			} else {

				$criteria->add(PluginPeer::AUTHOR_ID, $this->id);

				$this->collPlugins = PluginPeer::doSelectJoinTerm($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PluginPeer::AUTHOR_ID, $this->id);

			if (!isset($this->lastPluginCriteria) || !$this->lastPluginCriteria->equals($criteria)) {
				$this->collPlugins = PluginPeer::doSelectJoinTerm($criteria, $con, $join_behavior);
			}
		}
		$this->lastPluginCriteria = $criteria;

		return $this->collPlugins;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Author is new, it will return
	 * an empty collection; or if this Author has previously
	 * been saved, it will retrieve related Plugins from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Author.
	 */
	public function getPluginsJoinPluginTag($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AuthorPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlugins === null) {
			if ($this->isNew()) {
				$this->collPlugins = array();
			} else {

				$criteria->add(PluginPeer::AUTHOR_ID, $this->id);

				$this->collPlugins = PluginPeer::doSelectJoinPluginTag($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PluginPeer::AUTHOR_ID, $this->id);

			if (!isset($this->lastPluginCriteria) || !$this->lastPluginCriteria->equals($criteria)) {
				$this->collPlugins = PluginPeer::doSelectJoinPluginTag($criteria, $con, $join_behavior);
			}
		}
		$this->lastPluginCriteria = $criteria;

		return $this->collPlugins;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPlugins) {
				foreach ((array) $this->collPlugins as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPlugins = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseAuthor:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseAuthor::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseAuthor
