<?php

/**
 * Base class that represents a row from the 'plugin' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Dec 10 11:43:04 2009
 *
 * @package    lib.model.om
 */
abstract class BasePlugin extends BaseObject  implements Persistent {


  const PEER = 'PluginPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PluginPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the author_id field.
	 * @var        int
	 */
	protected $author_id;

	/**
	 * The value for the category_id field.
	 * @var        int
	 */
	protected $category_id;

	/**
	 * The value for the stable_tag_id field.
	 * @var        int
	 */
	protected $stable_tag_id;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the description_clean field.
	 * @var        string
	 */
	protected $description_clean;

	/**
	 * The value for the official field.
	 * @var        boolean
	 */
	protected $official;

	/**
	 * The value for the docsurl field.
	 * @var        string
	 */
	protected $docsurl;

	/**
	 * The value for the demourl field.
	 * @var        string
	 */
	protected $demourl;

	/**
	 * The value for the githubuser field.
	 * @var        string
	 */
	protected $githubuser;

	/**
	 * The value for the githubrepo field.
	 * @var        string
	 */
	protected $githubrepo;

	/**
	 * The value for the howtouse field.
	 * @var        string
	 */
	protected $howtouse;

	/**
	 * The value for the comments_count field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $comments_count;

	/**
	 * The value for the downloads_count field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $downloads_count;

	/**
	 * The value for the retrieved_at field.
	 * @var        string
	 */
	protected $retrieved_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        Author
	 */
	protected $aAuthor;

	/**
	 * @var        Term
	 */
	protected $aTerm;

	/**
	 * @var        PluginTag
	 */
	protected $aPluginTag;

	/**
	 * @var        array PluginSection[] Collection to store aggregation of PluginSection objects.
	 */
	protected $collPluginSections;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPluginSections.
	 */
	private $lastPluginSectionCriteria = null;

	/**
	 * @var        array PluginScreenshot[] Collection to store aggregation of PluginScreenshot objects.
	 */
	protected $collPluginScreenshots;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPluginScreenshots.
	 */
	private $lastPluginScreenshotCriteria = null;

	/**
	 * @var        array PluginDependency[] Collection to store aggregation of PluginDependency objects.
	 */
	protected $collPluginDependencys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPluginDependencys.
	 */
	private $lastPluginDependencyCriteria = null;

	/**
	 * @var        array PluginTag[] Collection to store aggregation of PluginTag objects.
	 */
	protected $collPluginTags;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPluginTags.
	 */
	private $lastPluginTagCriteria = null;

	/**
	 * @var        array TermRelationship[] Collection to store aggregation of TermRelationship objects.
	 */
	protected $collTermRelationships;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTermRelationships.
	 */
	private $lastTermRelationshipCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasePlugin object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->comments_count = 0;
		$this->downloads_count = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [author_id] column value.
	 * 
	 * @return     int
	 */
	public function getAuthorId()
	{
		return $this->author_id;
	}

	/**
	 * Get the [category_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryId()
	{
		return $this->category_id;
	}

	/**
	 * Get the [stable_tag_id] column value.
	 * 
	 * @return     int
	 */
	public function getStableTagId()
	{
		return $this->stable_tag_id;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [description_clean] column value.
	 * 
	 * @return     string
	 */
	public function getDescriptionClean()
	{
		return $this->description_clean;
	}

	/**
	 * Get the [official] column value.
	 * 
	 * @return     boolean
	 */
	public function getOfficial()
	{
		return $this->official;
	}

	/**
	 * Get the [docsurl] column value.
	 * 
	 * @return     string
	 */
	public function getDocsurl()
	{
		return $this->docsurl;
	}

	/**
	 * Get the [demourl] column value.
	 * 
	 * @return     string
	 */
	public function getDemourl()
	{
		return $this->demourl;
	}

	/**
	 * Get the [githubuser] column value.
	 * 
	 * @return     string
	 */
	public function getGithubuser()
	{
		return $this->githubuser;
	}

	/**
	 * Get the [githubrepo] column value.
	 * 
	 * @return     string
	 */
	public function getGithubrepo()
	{
		return $this->githubrepo;
	}

	/**
	 * Get the [howtouse] column value.
	 * 
	 * @return     string
	 */
	public function getHowtouse()
	{
		return $this->howtouse;
	}

	/**
	 * Get the [comments_count] column value.
	 * 
	 * @return     int
	 */
	public function getCommentsCount()
	{
		return $this->comments_count;
	}

	/**
	 * Get the [downloads_count] column value.
	 * 
	 * @return     int
	 */
	public function getDownloadsCount()
	{
		return $this->downloads_count;
	}

	/**
	 * Get the [optionally formatted] temporal [retrieved_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getRetrievedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->retrieved_at === null) {
			return null;
		}


		if ($this->retrieved_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->retrieved_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->retrieved_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PluginPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [author_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setAuthorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->author_id !== $v) {
			$this->author_id = $v;
			$this->modifiedColumns[] = PluginPeer::AUTHOR_ID;
		}

		if ($this->aAuthor !== null && $this->aAuthor->getId() !== $v) {
			$this->aAuthor = null;
		}

		return $this;
	} // setAuthorId()

	/**
	 * Set the value of [category_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setCategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_id !== $v) {
			$this->category_id = $v;
			$this->modifiedColumns[] = PluginPeer::CATEGORY_ID;
		}

		if ($this->aTerm !== null && $this->aTerm->getId() !== $v) {
			$this->aTerm = null;
		}

		return $this;
	} // setCategoryId()

	/**
	 * Set the value of [stable_tag_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setStableTagId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stable_tag_id !== $v) {
			$this->stable_tag_id = $v;
			$this->modifiedColumns[] = PluginPeer::STABLE_TAG_ID;
		}

		if ($this->aPluginTag !== null && $this->aPluginTag->getId() !== $v) {
			$this->aPluginTag = null;
		}

		return $this;
	} // setStableTagId()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = PluginPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = PluginPeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = PluginPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [description_clean] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setDescriptionClean($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description_clean !== $v) {
			$this->description_clean = $v;
			$this->modifiedColumns[] = PluginPeer::DESCRIPTION_CLEAN;
		}

		return $this;
	} // setDescriptionClean()

	/**
	 * Set the value of [official] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setOfficial($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->official !== $v) {
			$this->official = $v;
			$this->modifiedColumns[] = PluginPeer::OFFICIAL;
		}

		return $this;
	} // setOfficial()

	/**
	 * Set the value of [docsurl] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setDocsurl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->docsurl !== $v) {
			$this->docsurl = $v;
			$this->modifiedColumns[] = PluginPeer::DOCSURL;
		}

		return $this;
	} // setDocsurl()

	/**
	 * Set the value of [demourl] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setDemourl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->demourl !== $v) {
			$this->demourl = $v;
			$this->modifiedColumns[] = PluginPeer::DEMOURL;
		}

		return $this;
	} // setDemourl()

	/**
	 * Set the value of [githubuser] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setGithubuser($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->githubuser !== $v) {
			$this->githubuser = $v;
			$this->modifiedColumns[] = PluginPeer::GITHUBUSER;
		}

		return $this;
	} // setGithubuser()

	/**
	 * Set the value of [githubrepo] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setGithubrepo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->githubrepo !== $v) {
			$this->githubrepo = $v;
			$this->modifiedColumns[] = PluginPeer::GITHUBREPO;
		}

		return $this;
	} // setGithubrepo()

	/**
	 * Set the value of [howtouse] column.
	 * 
	 * @param      string $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setHowtouse($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->howtouse !== $v) {
			$this->howtouse = $v;
			$this->modifiedColumns[] = PluginPeer::HOWTOUSE;
		}

		return $this;
	} // setHowtouse()

	/**
	 * Set the value of [comments_count] column.
	 * 
	 * @param      int $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setCommentsCount($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->comments_count !== $v || $v === 0) {
			$this->comments_count = $v;
			$this->modifiedColumns[] = PluginPeer::COMMENTS_COUNT;
		}

		return $this;
	} // setCommentsCount()

	/**
	 * Set the value of [downloads_count] column.
	 * 
	 * @param      int $v new value
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setDownloadsCount($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->downloads_count !== $v || $v === 0) {
			$this->downloads_count = $v;
			$this->modifiedColumns[] = PluginPeer::DOWNLOADS_COUNT;
		}

		return $this;
	} // setDownloadsCount()

	/**
	 * Sets the value of [retrieved_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setRetrievedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->retrieved_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->retrieved_at !== null && $tmpDt = new DateTime($this->retrieved_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->retrieved_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PluginPeer::RETRIEVED_AT;
			}
		} // if either are not null

		return $this;
	} // setRetrievedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PluginPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Plugin The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PluginPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(PluginPeer::COMMENTS_COUNT,PluginPeer::DOWNLOADS_COUNT))) {
				return false;
			}

			if ($this->comments_count !== 0) {
				return false;
			}

			if ($this->downloads_count !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->author_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->category_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->stable_tag_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->title = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->slug = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->description = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->description_clean = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->official = ($row[$startcol + 8] !== null) ? (boolean) $row[$startcol + 8] : null;
			$this->docsurl = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->demourl = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->githubuser = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->githubrepo = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->howtouse = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->comments_count = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->downloads_count = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->retrieved_at = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->updated_at = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->created_at = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 19; // 19 = PluginPeer::NUM_COLUMNS - PluginPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Plugin object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAuthor !== null && $this->author_id !== $this->aAuthor->getId()) {
			$this->aAuthor = null;
		}
		if ($this->aTerm !== null && $this->category_id !== $this->aTerm->getId()) {
			$this->aTerm = null;
		}
		if ($this->aPluginTag !== null && $this->stable_tag_id !== $this->aPluginTag->getId()) {
			$this->aPluginTag = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PluginPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PluginPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAuthor = null;
			$this->aTerm = null;
			$this->aPluginTag = null;
			$this->collPluginSections = null;
			$this->lastPluginSectionCriteria = null;

			$this->collPluginScreenshots = null;
			$this->lastPluginScreenshotCriteria = null;

			$this->collPluginDependencys = null;
			$this->lastPluginDependencyCriteria = null;

			$this->collPluginTags = null;
			$this->lastPluginTagCriteria = null;

			$this->collTermRelationships = null;
			$this->lastTermRelationshipCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePlugin:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PluginPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			PluginPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasePlugin:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePlugin:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isModified() && !$this->isColumnModified(PluginPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

    if ($this->isNew() && !$this->isColumnModified(PluginPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PluginPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasePlugin:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			PluginPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAuthor !== null) {
				if ($this->aAuthor->isModified() || $this->aAuthor->isNew()) {
					$affectedRows += $this->aAuthor->save($con);
				}
				$this->setAuthor($this->aAuthor);
			}

			if ($this->aTerm !== null) {
				if ($this->aTerm->isModified() || $this->aTerm->isNew()) {
					$affectedRows += $this->aTerm->save($con);
				}
				$this->setTerm($this->aTerm);
			}

			if ($this->aPluginTag !== null) {
				if ($this->aPluginTag->isModified() || $this->aPluginTag->isNew()) {
					$affectedRows += $this->aPluginTag->save($con);
				}
				$this->setPluginTag($this->aPluginTag);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PluginPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PluginPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PluginPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPluginSections !== null) {
				foreach ($this->collPluginSections as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPluginScreenshots !== null) {
				foreach ($this->collPluginScreenshots as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPluginDependencys !== null) {
				foreach ($this->collPluginDependencys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPluginTags !== null) {
				foreach ($this->collPluginTags as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTermRelationships !== null) {
				foreach ($this->collTermRelationships as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAuthor !== null) {
				if (!$this->aAuthor->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAuthor->getValidationFailures());
				}
			}

			if ($this->aTerm !== null) {
				if (!$this->aTerm->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTerm->getValidationFailures());
				}
			}

			if ($this->aPluginTag !== null) {
				if (!$this->aPluginTag->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPluginTag->getValidationFailures());
				}
			}


			if (($retval = PluginPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPluginSections !== null) {
					foreach ($this->collPluginSections as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPluginScreenshots !== null) {
					foreach ($this->collPluginScreenshots as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPluginDependencys !== null) {
					foreach ($this->collPluginDependencys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPluginTags !== null) {
					foreach ($this->collPluginTags as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTermRelationships !== null) {
					foreach ($this->collTermRelationships as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PluginPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getAuthorId();
				break;
			case 2:
				return $this->getCategoryId();
				break;
			case 3:
				return $this->getStableTagId();
				break;
			case 4:
				return $this->getTitle();
				break;
			case 5:
				return $this->getSlug();
				break;
			case 6:
				return $this->getDescription();
				break;
			case 7:
				return $this->getDescriptionClean();
				break;
			case 8:
				return $this->getOfficial();
				break;
			case 9:
				return $this->getDocsurl();
				break;
			case 10:
				return $this->getDemourl();
				break;
			case 11:
				return $this->getGithubuser();
				break;
			case 12:
				return $this->getGithubrepo();
				break;
			case 13:
				return $this->getHowtouse();
				break;
			case 14:
				return $this->getCommentsCount();
				break;
			case 15:
				return $this->getDownloadsCount();
				break;
			case 16:
				return $this->getRetrievedAt();
				break;
			case 17:
				return $this->getUpdatedAt();
				break;
			case 18:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PluginPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getAuthorId(),
			$keys[2] => $this->getCategoryId(),
			$keys[3] => $this->getStableTagId(),
			$keys[4] => $this->getTitle(),
			$keys[5] => $this->getSlug(),
			$keys[6] => $this->getDescription(),
			$keys[7] => $this->getDescriptionClean(),
			$keys[8] => $this->getOfficial(),
			$keys[9] => $this->getDocsurl(),
			$keys[10] => $this->getDemourl(),
			$keys[11] => $this->getGithubuser(),
			$keys[12] => $this->getGithubrepo(),
			$keys[13] => $this->getHowtouse(),
			$keys[14] => $this->getCommentsCount(),
			$keys[15] => $this->getDownloadsCount(),
			$keys[16] => $this->getRetrievedAt(),
			$keys[17] => $this->getUpdatedAt(),
			$keys[18] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PluginPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setAuthorId($value);
				break;
			case 2:
				$this->setCategoryId($value);
				break;
			case 3:
				$this->setStableTagId($value);
				break;
			case 4:
				$this->setTitle($value);
				break;
			case 5:
				$this->setSlug($value);
				break;
			case 6:
				$this->setDescription($value);
				break;
			case 7:
				$this->setDescriptionClean($value);
				break;
			case 8:
				$this->setOfficial($value);
				break;
			case 9:
				$this->setDocsurl($value);
				break;
			case 10:
				$this->setDemourl($value);
				break;
			case 11:
				$this->setGithubuser($value);
				break;
			case 12:
				$this->setGithubrepo($value);
				break;
			case 13:
				$this->setHowtouse($value);
				break;
			case 14:
				$this->setCommentsCount($value);
				break;
			case 15:
				$this->setDownloadsCount($value);
				break;
			case 16:
				$this->setRetrievedAt($value);
				break;
			case 17:
				$this->setUpdatedAt($value);
				break;
			case 18:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PluginPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setAuthorId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCategoryId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setStableTagId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTitle($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSlug($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDescription($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDescriptionClean($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setOfficial($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDocsurl($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDemourl($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setGithubuser($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setGithubrepo($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setHowtouse($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCommentsCount($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setDownloadsCount($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setRetrievedAt($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setUpdatedAt($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setCreatedAt($arr[$keys[18]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PluginPeer::DATABASE_NAME);

		if ($this->isColumnModified(PluginPeer::ID)) $criteria->add(PluginPeer::ID, $this->id);
		if ($this->isColumnModified(PluginPeer::AUTHOR_ID)) $criteria->add(PluginPeer::AUTHOR_ID, $this->author_id);
		if ($this->isColumnModified(PluginPeer::CATEGORY_ID)) $criteria->add(PluginPeer::CATEGORY_ID, $this->category_id);
		if ($this->isColumnModified(PluginPeer::STABLE_TAG_ID)) $criteria->add(PluginPeer::STABLE_TAG_ID, $this->stable_tag_id);
		if ($this->isColumnModified(PluginPeer::TITLE)) $criteria->add(PluginPeer::TITLE, $this->title);
		if ($this->isColumnModified(PluginPeer::SLUG)) $criteria->add(PluginPeer::SLUG, $this->slug);
		if ($this->isColumnModified(PluginPeer::DESCRIPTION)) $criteria->add(PluginPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(PluginPeer::DESCRIPTION_CLEAN)) $criteria->add(PluginPeer::DESCRIPTION_CLEAN, $this->description_clean);
		if ($this->isColumnModified(PluginPeer::OFFICIAL)) $criteria->add(PluginPeer::OFFICIAL, $this->official);
		if ($this->isColumnModified(PluginPeer::DOCSURL)) $criteria->add(PluginPeer::DOCSURL, $this->docsurl);
		if ($this->isColumnModified(PluginPeer::DEMOURL)) $criteria->add(PluginPeer::DEMOURL, $this->demourl);
		if ($this->isColumnModified(PluginPeer::GITHUBUSER)) $criteria->add(PluginPeer::GITHUBUSER, $this->githubuser);
		if ($this->isColumnModified(PluginPeer::GITHUBREPO)) $criteria->add(PluginPeer::GITHUBREPO, $this->githubrepo);
		if ($this->isColumnModified(PluginPeer::HOWTOUSE)) $criteria->add(PluginPeer::HOWTOUSE, $this->howtouse);
		if ($this->isColumnModified(PluginPeer::COMMENTS_COUNT)) $criteria->add(PluginPeer::COMMENTS_COUNT, $this->comments_count);
		if ($this->isColumnModified(PluginPeer::DOWNLOADS_COUNT)) $criteria->add(PluginPeer::DOWNLOADS_COUNT, $this->downloads_count);
		if ($this->isColumnModified(PluginPeer::RETRIEVED_AT)) $criteria->add(PluginPeer::RETRIEVED_AT, $this->retrieved_at);
		if ($this->isColumnModified(PluginPeer::UPDATED_AT)) $criteria->add(PluginPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(PluginPeer::CREATED_AT)) $criteria->add(PluginPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PluginPeer::DATABASE_NAME);

		$criteria->add(PluginPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Plugin (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setAuthorId($this->author_id);

		$copyObj->setCategoryId($this->category_id);

		$copyObj->setStableTagId($this->stable_tag_id);

		$copyObj->setTitle($this->title);

		$copyObj->setSlug($this->slug);

		$copyObj->setDescription($this->description);

		$copyObj->setDescriptionClean($this->description_clean);

		$copyObj->setOfficial($this->official);

		$copyObj->setDocsurl($this->docsurl);

		$copyObj->setDemourl($this->demourl);

		$copyObj->setGithubuser($this->githubuser);

		$copyObj->setGithubrepo($this->githubrepo);

		$copyObj->setHowtouse($this->howtouse);

		$copyObj->setCommentsCount($this->comments_count);

		$copyObj->setDownloadsCount($this->downloads_count);

		$copyObj->setRetrievedAt($this->retrieved_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPluginSections() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPluginSection($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPluginScreenshots() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPluginScreenshot($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPluginDependencys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPluginDependency($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPluginTags() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPluginTag($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTermRelationships() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTermRelationship($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Plugin Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PluginPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PluginPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Author object.
	 *
	 * @param      Author $v
	 * @return     Plugin The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAuthor(Author $v = null)
	{
		if ($v === null) {
			$this->setAuthorId(NULL);
		} else {
			$this->setAuthorId($v->getId());
		}

		$this->aAuthor = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Author object, it will not be re-added.
		if ($v !== null) {
			$v->addPlugin($this);
		}

		return $this;
	}


	/**
	 * Get the associated Author object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Author The associated Author object.
	 * @throws     PropelException
	 */
	public function getAuthor(PropelPDO $con = null)
	{
		if ($this->aAuthor === null && ($this->author_id !== null)) {
			$c = new Criteria(AuthorPeer::DATABASE_NAME);
			$c->add(AuthorPeer::ID, $this->author_id);
			$this->aAuthor = AuthorPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAuthor->addPlugins($this);
			 */
		}
		return $this->aAuthor;
	}

	/**
	 * Declares an association between this object and a Term object.
	 *
	 * @param      Term $v
	 * @return     Plugin The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTerm(Term $v = null)
	{
		if ($v === null) {
			$this->setCategoryId(NULL);
		} else {
			$this->setCategoryId($v->getId());
		}

		$this->aTerm = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Term object, it will not be re-added.
		if ($v !== null) {
			$v->addPlugin($this);
		}

		return $this;
	}


	/**
	 * Get the associated Term object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Term The associated Term object.
	 * @throws     PropelException
	 */
	public function getTerm(PropelPDO $con = null)
	{
		if ($this->aTerm === null && ($this->category_id !== null)) {
			$c = new Criteria(TermPeer::DATABASE_NAME);
			$c->add(TermPeer::ID, $this->category_id);
			$this->aTerm = TermPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTerm->addPlugins($this);
			 */
		}
		return $this->aTerm;
	}

	/**
	 * Declares an association between this object and a PluginTag object.
	 *
	 * @param      PluginTag $v
	 * @return     Plugin The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPluginTag(PluginTag $v = null)
	{
		if ($v === null) {
			$this->setStableTagId(NULL);
		} else {
			$this->setStableTagId($v->getId());
		}

		$this->aPluginTag = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the PluginTag object, it will not be re-added.
		if ($v !== null) {
			$v->addPlugin($this);
		}

		return $this;
	}


	/**
	 * Get the associated PluginTag object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     PluginTag The associated PluginTag object.
	 * @throws     PropelException
	 */
	public function getPluginTag(PropelPDO $con = null)
	{
		if ($this->aPluginTag === null && ($this->stable_tag_id !== null)) {
			$c = new Criteria(PluginTagPeer::DATABASE_NAME);
			$c->add(PluginTagPeer::ID, $this->stable_tag_id);
			$this->aPluginTag = PluginTagPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPluginTag->addPlugins($this);
			 */
		}
		return $this->aPluginTag;
	}

	/**
	 * Clears out the collPluginSections collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPluginSections()
	 */
	public function clearPluginSections()
	{
		$this->collPluginSections = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPluginSections collection (array).
	 *
	 * By default this just sets the collPluginSections collection to an empty array (like clearcollPluginSections());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPluginSections()
	{
		$this->collPluginSections = array();
	}

	/**
	 * Gets an array of PluginSection objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Plugin has previously been saved, it will retrieve
	 * related PluginSections from storage. If this Plugin is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array PluginSection[]
	 * @throws     PropelException
	 */
	public function getPluginSections($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPluginSections === null) {
			if ($this->isNew()) {
			   $this->collPluginSections = array();
			} else {

				$criteria->add(PluginSectionPeer::PLUGIN_ID, $this->id);

				PluginSectionPeer::addSelectColumns($criteria);
				$this->collPluginSections = PluginSectionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PluginSectionPeer::PLUGIN_ID, $this->id);

				PluginSectionPeer::addSelectColumns($criteria);
				if (!isset($this->lastPluginSectionCriteria) || !$this->lastPluginSectionCriteria->equals($criteria)) {
					$this->collPluginSections = PluginSectionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPluginSectionCriteria = $criteria;
		return $this->collPluginSections;
	}

	/**
	 * Returns the number of related PluginSection objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related PluginSection objects.
	 * @throws     PropelException
	 */
	public function countPluginSections(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPluginSections === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PluginSectionPeer::PLUGIN_ID, $this->id);

				$count = PluginSectionPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PluginSectionPeer::PLUGIN_ID, $this->id);

				if (!isset($this->lastPluginSectionCriteria) || !$this->lastPluginSectionCriteria->equals($criteria)) {
					$count = PluginSectionPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPluginSections);
				}
			} else {
				$count = count($this->collPluginSections);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a PluginSection object to this object
	 * through the PluginSection foreign key attribute.
	 *
	 * @param      PluginSection $l PluginSection
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPluginSection(PluginSection $l)
	{
		if ($this->collPluginSections === null) {
			$this->initPluginSections();
		}
		if (!in_array($l, $this->collPluginSections, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPluginSections, $l);
			$l->setPlugin($this);
		}
	}

	/**
	 * Clears out the collPluginScreenshots collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPluginScreenshots()
	 */
	public function clearPluginScreenshots()
	{
		$this->collPluginScreenshots = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPluginScreenshots collection (array).
	 *
	 * By default this just sets the collPluginScreenshots collection to an empty array (like clearcollPluginScreenshots());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPluginScreenshots()
	{
		$this->collPluginScreenshots = array();
	}

	/**
	 * Gets an array of PluginScreenshot objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Plugin has previously been saved, it will retrieve
	 * related PluginScreenshots from storage. If this Plugin is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array PluginScreenshot[]
	 * @throws     PropelException
	 */
	public function getPluginScreenshots($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPluginScreenshots === null) {
			if ($this->isNew()) {
			   $this->collPluginScreenshots = array();
			} else {

				$criteria->add(PluginScreenshotPeer::PLUGIN_ID, $this->id);

				PluginScreenshotPeer::addSelectColumns($criteria);
				$this->collPluginScreenshots = PluginScreenshotPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PluginScreenshotPeer::PLUGIN_ID, $this->id);

				PluginScreenshotPeer::addSelectColumns($criteria);
				if (!isset($this->lastPluginScreenshotCriteria) || !$this->lastPluginScreenshotCriteria->equals($criteria)) {
					$this->collPluginScreenshots = PluginScreenshotPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPluginScreenshotCriteria = $criteria;
		return $this->collPluginScreenshots;
	}

	/**
	 * Returns the number of related PluginScreenshot objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related PluginScreenshot objects.
	 * @throws     PropelException
	 */
	public function countPluginScreenshots(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPluginScreenshots === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PluginScreenshotPeer::PLUGIN_ID, $this->id);

				$count = PluginScreenshotPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PluginScreenshotPeer::PLUGIN_ID, $this->id);

				if (!isset($this->lastPluginScreenshotCriteria) || !$this->lastPluginScreenshotCriteria->equals($criteria)) {
					$count = PluginScreenshotPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPluginScreenshots);
				}
			} else {
				$count = count($this->collPluginScreenshots);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a PluginScreenshot object to this object
	 * through the PluginScreenshot foreign key attribute.
	 *
	 * @param      PluginScreenshot $l PluginScreenshot
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPluginScreenshot(PluginScreenshot $l)
	{
		if ($this->collPluginScreenshots === null) {
			$this->initPluginScreenshots();
		}
		if (!in_array($l, $this->collPluginScreenshots, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPluginScreenshots, $l);
			$l->setPlugin($this);
		}
	}

	/**
	 * Clears out the collPluginDependencys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPluginDependencys()
	 */
	public function clearPluginDependencys()
	{
		$this->collPluginDependencys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPluginDependencys collection (array).
	 *
	 * By default this just sets the collPluginDependencys collection to an empty array (like clearcollPluginDependencys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPluginDependencys()
	{
		$this->collPluginDependencys = array();
	}

	/**
	 * Gets an array of PluginDependency objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Plugin has previously been saved, it will retrieve
	 * related PluginDependencys from storage. If this Plugin is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array PluginDependency[]
	 * @throws     PropelException
	 */
	public function getPluginDependencys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPluginDependencys === null) {
			if ($this->isNew()) {
			   $this->collPluginDependencys = array();
			} else {

				$criteria->add(PluginDependencyPeer::PLUGIN_ID, $this->id);

				PluginDependencyPeer::addSelectColumns($criteria);
				$this->collPluginDependencys = PluginDependencyPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PluginDependencyPeer::PLUGIN_ID, $this->id);

				PluginDependencyPeer::addSelectColumns($criteria);
				if (!isset($this->lastPluginDependencyCriteria) || !$this->lastPluginDependencyCriteria->equals($criteria)) {
					$this->collPluginDependencys = PluginDependencyPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPluginDependencyCriteria = $criteria;
		return $this->collPluginDependencys;
	}

	/**
	 * Returns the number of related PluginDependency objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related PluginDependency objects.
	 * @throws     PropelException
	 */
	public function countPluginDependencys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPluginDependencys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PluginDependencyPeer::PLUGIN_ID, $this->id);

				$count = PluginDependencyPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PluginDependencyPeer::PLUGIN_ID, $this->id);

				if (!isset($this->lastPluginDependencyCriteria) || !$this->lastPluginDependencyCriteria->equals($criteria)) {
					$count = PluginDependencyPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPluginDependencys);
				}
			} else {
				$count = count($this->collPluginDependencys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a PluginDependency object to this object
	 * through the PluginDependency foreign key attribute.
	 *
	 * @param      PluginDependency $l PluginDependency
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPluginDependency(PluginDependency $l)
	{
		if ($this->collPluginDependencys === null) {
			$this->initPluginDependencys();
		}
		if (!in_array($l, $this->collPluginDependencys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPluginDependencys, $l);
			$l->setPlugin($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Plugin is new, it will return
	 * an empty collection; or if this Plugin has previously
	 * been saved, it will retrieve related PluginDependencys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Plugin.
	 */
	public function getPluginDependencysJoinPluginTag($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPluginDependencys === null) {
			if ($this->isNew()) {
				$this->collPluginDependencys = array();
			} else {

				$criteria->add(PluginDependencyPeer::PLUGIN_ID, $this->id);

				$this->collPluginDependencys = PluginDependencyPeer::doSelectJoinPluginTag($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PluginDependencyPeer::PLUGIN_ID, $this->id);

			if (!isset($this->lastPluginDependencyCriteria) || !$this->lastPluginDependencyCriteria->equals($criteria)) {
				$this->collPluginDependencys = PluginDependencyPeer::doSelectJoinPluginTag($criteria, $con, $join_behavior);
			}
		}
		$this->lastPluginDependencyCriteria = $criteria;

		return $this->collPluginDependencys;
	}

	/**
	 * Clears out the collPluginTags collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPluginTags()
	 */
	public function clearPluginTags()
	{
		$this->collPluginTags = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPluginTags collection (array).
	 *
	 * By default this just sets the collPluginTags collection to an empty array (like clearcollPluginTags());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPluginTags()
	{
		$this->collPluginTags = array();
	}

	/**
	 * Gets an array of PluginTag objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Plugin has previously been saved, it will retrieve
	 * related PluginTags from storage. If this Plugin is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array PluginTag[]
	 * @throws     PropelException
	 */
	public function getPluginTags($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPluginTags === null) {
			if ($this->isNew()) {
			   $this->collPluginTags = array();
			} else {

				$criteria->add(PluginTagPeer::PLUGIN_ID, $this->id);

				PluginTagPeer::addSelectColumns($criteria);
				$this->collPluginTags = PluginTagPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PluginTagPeer::PLUGIN_ID, $this->id);

				PluginTagPeer::addSelectColumns($criteria);
				if (!isset($this->lastPluginTagCriteria) || !$this->lastPluginTagCriteria->equals($criteria)) {
					$this->collPluginTags = PluginTagPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPluginTagCriteria = $criteria;
		return $this->collPluginTags;
	}

	/**
	 * Returns the number of related PluginTag objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related PluginTag objects.
	 * @throws     PropelException
	 */
	public function countPluginTags(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPluginTags === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PluginTagPeer::PLUGIN_ID, $this->id);

				$count = PluginTagPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PluginTagPeer::PLUGIN_ID, $this->id);

				if (!isset($this->lastPluginTagCriteria) || !$this->lastPluginTagCriteria->equals($criteria)) {
					$count = PluginTagPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPluginTags);
				}
			} else {
				$count = count($this->collPluginTags);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a PluginTag object to this object
	 * through the PluginTag foreign key attribute.
	 *
	 * @param      PluginTag $l PluginTag
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPluginTag(PluginTag $l)
	{
		if ($this->collPluginTags === null) {
			$this->initPluginTags();
		}
		if (!in_array($l, $this->collPluginTags, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPluginTags, $l);
			$l->setPlugin($this);
		}
	}

	/**
	 * Clears out the collTermRelationships collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTermRelationships()
	 */
	public function clearTermRelationships()
	{
		$this->collTermRelationships = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTermRelationships collection (array).
	 *
	 * By default this just sets the collTermRelationships collection to an empty array (like clearcollTermRelationships());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTermRelationships()
	{
		$this->collTermRelationships = array();
	}

	/**
	 * Gets an array of TermRelationship objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Plugin has previously been saved, it will retrieve
	 * related TermRelationships from storage. If this Plugin is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TermRelationship[]
	 * @throws     PropelException
	 */
	public function getTermRelationships($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTermRelationships === null) {
			if ($this->isNew()) {
			   $this->collTermRelationships = array();
			} else {

				$criteria->add(TermRelationshipPeer::PLUGIN_ID, $this->id);

				TermRelationshipPeer::addSelectColumns($criteria);
				$this->collTermRelationships = TermRelationshipPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TermRelationshipPeer::PLUGIN_ID, $this->id);

				TermRelationshipPeer::addSelectColumns($criteria);
				if (!isset($this->lastTermRelationshipCriteria) || !$this->lastTermRelationshipCriteria->equals($criteria)) {
					$this->collTermRelationships = TermRelationshipPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTermRelationshipCriteria = $criteria;
		return $this->collTermRelationships;
	}

	/**
	 * Returns the number of related TermRelationship objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TermRelationship objects.
	 * @throws     PropelException
	 */
	public function countTermRelationships(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTermRelationships === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TermRelationshipPeer::PLUGIN_ID, $this->id);

				$count = TermRelationshipPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TermRelationshipPeer::PLUGIN_ID, $this->id);

				if (!isset($this->lastTermRelationshipCriteria) || !$this->lastTermRelationshipCriteria->equals($criteria)) {
					$count = TermRelationshipPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collTermRelationships);
				}
			} else {
				$count = count($this->collTermRelationships);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TermRelationship object to this object
	 * through the TermRelationship foreign key attribute.
	 *
	 * @param      TermRelationship $l TermRelationship
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTermRelationship(TermRelationship $l)
	{
		if ($this->collTermRelationships === null) {
			$this->initTermRelationships();
		}
		if (!in_array($l, $this->collTermRelationships, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTermRelationships, $l);
			$l->setPlugin($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Plugin is new, it will return
	 * an empty collection; or if this Plugin has previously
	 * been saved, it will retrieve related TermRelationships from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Plugin.
	 */
	public function getTermRelationshipsJoinTerm($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTermRelationships === null) {
			if ($this->isNew()) {
				$this->collTermRelationships = array();
			} else {

				$criteria->add(TermRelationshipPeer::PLUGIN_ID, $this->id);

				$this->collTermRelationships = TermRelationshipPeer::doSelectJoinTerm($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TermRelationshipPeer::PLUGIN_ID, $this->id);

			if (!isset($this->lastTermRelationshipCriteria) || !$this->lastTermRelationshipCriteria->equals($criteria)) {
				$this->collTermRelationships = TermRelationshipPeer::doSelectJoinTerm($criteria, $con, $join_behavior);
			}
		}
		$this->lastTermRelationshipCriteria = $criteria;

		return $this->collTermRelationships;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPluginSections) {
				foreach ((array) $this->collPluginSections as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPluginScreenshots) {
				foreach ((array) $this->collPluginScreenshots as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPluginDependencys) {
				foreach ((array) $this->collPluginDependencys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPluginTags) {
				foreach ((array) $this->collPluginTags as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTermRelationships) {
				foreach ((array) $this->collTermRelationships as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPluginSections = null;
		$this->collPluginScreenshots = null;
		$this->collPluginDependencys = null;
		$this->collPluginTags = null;
		$this->collTermRelationships = null;
			$this->aAuthor = null;
			$this->aTerm = null;
			$this->aPluginTag = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasePlugin:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasePlugin::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasePlugin
