<?php

/**
 * Base class that represents a row from the 'plugin_tag' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Dec 10 11:43:04 2009
 *
 * @package    lib.model.om
 */
abstract class BasePluginTag extends BaseObject  implements Persistent {


  const PEER = 'PluginTagPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PluginTagPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the plugin_id field.
	 * @var        int
	 */
	protected $plugin_id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the downloads_count field.
	 * @var        int
	 */
	protected $downloads_count;

	/**
	 * The value for the current field.
	 * @var        boolean
	 */
	protected $current;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        Plugin
	 */
	protected $aPlugin;

	/**
	 * @var        array Plugin[] Collection to store aggregation of Plugin objects.
	 */
	protected $collPlugins;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPlugins.
	 */
	private $lastPluginCriteria = null;

	/**
	 * @var        array PluginDependency[] Collection to store aggregation of PluginDependency objects.
	 */
	protected $collPluginDependencys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPluginDependencys.
	 */
	private $lastPluginDependencyCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasePluginTag object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [plugin_id] column value.
	 * 
	 * @return     int
	 */
	public function getPluginId()
	{
		return $this->plugin_id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [downloads_count] column value.
	 * 
	 * @return     int
	 */
	public function getDownloadsCount()
	{
		return $this->downloads_count;
	}

	/**
	 * Get the [current] column value.
	 * 
	 * @return     boolean
	 */
	public function getCurrent()
	{
		return $this->current;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     PluginTag The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PluginTagPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [plugin_id] column.
	 * 
	 * @param      int $v new value
	 * @return     PluginTag The current object (for fluent API support)
	 */
	public function setPluginId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->plugin_id !== $v) {
			$this->plugin_id = $v;
			$this->modifiedColumns[] = PluginTagPeer::PLUGIN_ID;
		}

		if ($this->aPlugin !== null && $this->aPlugin->getId() !== $v) {
			$this->aPlugin = null;
		}

		return $this;
	} // setPluginId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     PluginTag The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = PluginTagPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [downloads_count] column.
	 * 
	 * @param      int $v new value
	 * @return     PluginTag The current object (for fluent API support)
	 */
	public function setDownloadsCount($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->downloads_count !== $v) {
			$this->downloads_count = $v;
			$this->modifiedColumns[] = PluginTagPeer::DOWNLOADS_COUNT;
		}

		return $this;
	} // setDownloadsCount()

	/**
	 * Set the value of [current] column.
	 * 
	 * @param      boolean $v new value
	 * @return     PluginTag The current object (for fluent API support)
	 */
	public function setCurrent($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->current !== $v) {
			$this->current = $v;
			$this->modifiedColumns[] = PluginTagPeer::CURRENT;
		}

		return $this;
	} // setCurrent()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     PluginTag The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PluginTagPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->plugin_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->downloads_count = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->current = ($row[$startcol + 4] !== null) ? (boolean) $row[$startcol + 4] : null;
			$this->created_at = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = PluginTagPeer::NUM_COLUMNS - PluginTagPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating PluginTag object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPlugin !== null && $this->plugin_id !== $this->aPlugin->getId()) {
			$this->aPlugin = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PluginTagPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PluginTagPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPlugin = null;
			$this->collPlugins = null;
			$this->lastPluginCriteria = null;

			$this->collPluginDependencys = null;
			$this->lastPluginDependencyCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePluginTag:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PluginTagPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			PluginTagPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasePluginTag:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePluginTag:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(PluginTagPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PluginTagPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasePluginTag:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			PluginTagPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPlugin !== null) {
				if ($this->aPlugin->isModified() || $this->aPlugin->isNew()) {
					$affectedRows += $this->aPlugin->save($con);
				}
				$this->setPlugin($this->aPlugin);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PluginTagPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PluginTagPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PluginTagPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPlugins !== null) {
				foreach ($this->collPlugins as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPluginDependencys !== null) {
				foreach ($this->collPluginDependencys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPlugin !== null) {
				if (!$this->aPlugin->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPlugin->getValidationFailures());
				}
			}


			if (($retval = PluginTagPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPlugins !== null) {
					foreach ($this->collPlugins as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPluginDependencys !== null) {
					foreach ($this->collPluginDependencys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PluginTagPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPluginId();
				break;
			case 2:
				return $this->getName();
				break;
			case 3:
				return $this->getDownloadsCount();
				break;
			case 4:
				return $this->getCurrent();
				break;
			case 5:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PluginTagPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPluginId(),
			$keys[2] => $this->getName(),
			$keys[3] => $this->getDownloadsCount(),
			$keys[4] => $this->getCurrent(),
			$keys[5] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PluginTagPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPluginId($value);
				break;
			case 2:
				$this->setName($value);
				break;
			case 3:
				$this->setDownloadsCount($value);
				break;
			case 4:
				$this->setCurrent($value);
				break;
			case 5:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PluginTagPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPluginId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDownloadsCount($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCurrent($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCreatedAt($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);

		if ($this->isColumnModified(PluginTagPeer::ID)) $criteria->add(PluginTagPeer::ID, $this->id);
		if ($this->isColumnModified(PluginTagPeer::PLUGIN_ID)) $criteria->add(PluginTagPeer::PLUGIN_ID, $this->plugin_id);
		if ($this->isColumnModified(PluginTagPeer::NAME)) $criteria->add(PluginTagPeer::NAME, $this->name);
		if ($this->isColumnModified(PluginTagPeer::DOWNLOADS_COUNT)) $criteria->add(PluginTagPeer::DOWNLOADS_COUNT, $this->downloads_count);
		if ($this->isColumnModified(PluginTagPeer::CURRENT)) $criteria->add(PluginTagPeer::CURRENT, $this->current);
		if ($this->isColumnModified(PluginTagPeer::CREATED_AT)) $criteria->add(PluginTagPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);

		$criteria->add(PluginTagPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of PluginTag (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPluginId($this->plugin_id);

		$copyObj->setName($this->name);

		$copyObj->setDownloadsCount($this->downloads_count);

		$copyObj->setCurrent($this->current);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPlugins() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPlugin($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPluginDependencys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPluginDependency($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     PluginTag Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PluginTagPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PluginTagPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Plugin object.
	 *
	 * @param      Plugin $v
	 * @return     PluginTag The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPlugin(Plugin $v = null)
	{
		if ($v === null) {
			$this->setPluginId(NULL);
		} else {
			$this->setPluginId($v->getId());
		}

		$this->aPlugin = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Plugin object, it will not be re-added.
		if ($v !== null) {
			$v->addPluginTag($this);
		}

		return $this;
	}


	/**
	 * Get the associated Plugin object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Plugin The associated Plugin object.
	 * @throws     PropelException
	 */
	public function getPlugin(PropelPDO $con = null)
	{
		if ($this->aPlugin === null && ($this->plugin_id !== null)) {
			$c = new Criteria(PluginPeer::DATABASE_NAME);
			$c->add(PluginPeer::ID, $this->plugin_id);
			$this->aPlugin = PluginPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPlugin->addPluginTags($this);
			 */
		}
		return $this->aPlugin;
	}

	/**
	 * Clears out the collPlugins collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPlugins()
	 */
	public function clearPlugins()
	{
		$this->collPlugins = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPlugins collection (array).
	 *
	 * By default this just sets the collPlugins collection to an empty array (like clearcollPlugins());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPlugins()
	{
		$this->collPlugins = array();
	}

	/**
	 * Gets an array of Plugin objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this PluginTag has previously been saved, it will retrieve
	 * related Plugins from storage. If this PluginTag is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Plugin[]
	 * @throws     PropelException
	 */
	public function getPlugins($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlugins === null) {
			if ($this->isNew()) {
			   $this->collPlugins = array();
			} else {

				$criteria->add(PluginPeer::STABLE_TAG_ID, $this->id);

				PluginPeer::addSelectColumns($criteria);
				$this->collPlugins = PluginPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PluginPeer::STABLE_TAG_ID, $this->id);

				PluginPeer::addSelectColumns($criteria);
				if (!isset($this->lastPluginCriteria) || !$this->lastPluginCriteria->equals($criteria)) {
					$this->collPlugins = PluginPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPluginCriteria = $criteria;
		return $this->collPlugins;
	}

	/**
	 * Returns the number of related Plugin objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Plugin objects.
	 * @throws     PropelException
	 */
	public function countPlugins(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPlugins === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PluginPeer::STABLE_TAG_ID, $this->id);

				$count = PluginPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PluginPeer::STABLE_TAG_ID, $this->id);

				if (!isset($this->lastPluginCriteria) || !$this->lastPluginCriteria->equals($criteria)) {
					$count = PluginPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPlugins);
				}
			} else {
				$count = count($this->collPlugins);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Plugin object to this object
	 * through the Plugin foreign key attribute.
	 *
	 * @param      Plugin $l Plugin
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPlugin(Plugin $l)
	{
		if ($this->collPlugins === null) {
			$this->initPlugins();
		}
		if (!in_array($l, $this->collPlugins, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPlugins, $l);
			$l->setPluginTag($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PluginTag is new, it will return
	 * an empty collection; or if this PluginTag has previously
	 * been saved, it will retrieve related Plugins from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PluginTag.
	 */
	public function getPluginsJoinAuthor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlugins === null) {
			if ($this->isNew()) {
				$this->collPlugins = array();
			} else {

				$criteria->add(PluginPeer::STABLE_TAG_ID, $this->id);

				$this->collPlugins = PluginPeer::doSelectJoinAuthor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PluginPeer::STABLE_TAG_ID, $this->id);

			if (!isset($this->lastPluginCriteria) || !$this->lastPluginCriteria->equals($criteria)) {
				$this->collPlugins = PluginPeer::doSelectJoinAuthor($criteria, $con, $join_behavior);
			}
		}
		$this->lastPluginCriteria = $criteria;

		return $this->collPlugins;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PluginTag is new, it will return
	 * an empty collection; or if this PluginTag has previously
	 * been saved, it will retrieve related Plugins from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PluginTag.
	 */
	public function getPluginsJoinTerm($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPlugins === null) {
			if ($this->isNew()) {
				$this->collPlugins = array();
			} else {

				$criteria->add(PluginPeer::STABLE_TAG_ID, $this->id);

				$this->collPlugins = PluginPeer::doSelectJoinTerm($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PluginPeer::STABLE_TAG_ID, $this->id);

			if (!isset($this->lastPluginCriteria) || !$this->lastPluginCriteria->equals($criteria)) {
				$this->collPlugins = PluginPeer::doSelectJoinTerm($criteria, $con, $join_behavior);
			}
		}
		$this->lastPluginCriteria = $criteria;

		return $this->collPlugins;
	}

	/**
	 * Clears out the collPluginDependencys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPluginDependencys()
	 */
	public function clearPluginDependencys()
	{
		$this->collPluginDependencys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPluginDependencys collection (array).
	 *
	 * By default this just sets the collPluginDependencys collection to an empty array (like clearcollPluginDependencys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPluginDependencys()
	{
		$this->collPluginDependencys = array();
	}

	/**
	 * Gets an array of PluginDependency objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this PluginTag has previously been saved, it will retrieve
	 * related PluginDependencys from storage. If this PluginTag is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array PluginDependency[]
	 * @throws     PropelException
	 */
	public function getPluginDependencys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPluginDependencys === null) {
			if ($this->isNew()) {
			   $this->collPluginDependencys = array();
			} else {

				$criteria->add(PluginDependencyPeer::PLUGIN_TAG_ID, $this->id);

				PluginDependencyPeer::addSelectColumns($criteria);
				$this->collPluginDependencys = PluginDependencyPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PluginDependencyPeer::PLUGIN_TAG_ID, $this->id);

				PluginDependencyPeer::addSelectColumns($criteria);
				if (!isset($this->lastPluginDependencyCriteria) || !$this->lastPluginDependencyCriteria->equals($criteria)) {
					$this->collPluginDependencys = PluginDependencyPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPluginDependencyCriteria = $criteria;
		return $this->collPluginDependencys;
	}

	/**
	 * Returns the number of related PluginDependency objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related PluginDependency objects.
	 * @throws     PropelException
	 */
	public function countPluginDependencys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPluginDependencys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PluginDependencyPeer::PLUGIN_TAG_ID, $this->id);

				$count = PluginDependencyPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PluginDependencyPeer::PLUGIN_TAG_ID, $this->id);

				if (!isset($this->lastPluginDependencyCriteria) || !$this->lastPluginDependencyCriteria->equals($criteria)) {
					$count = PluginDependencyPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collPluginDependencys);
				}
			} else {
				$count = count($this->collPluginDependencys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a PluginDependency object to this object
	 * through the PluginDependency foreign key attribute.
	 *
	 * @param      PluginDependency $l PluginDependency
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPluginDependency(PluginDependency $l)
	{
		if ($this->collPluginDependencys === null) {
			$this->initPluginDependencys();
		}
		if (!in_array($l, $this->collPluginDependencys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPluginDependencys, $l);
			$l->setPluginTag($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this PluginTag is new, it will return
	 * an empty collection; or if this PluginTag has previously
	 * been saved, it will retrieve related PluginDependencys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in PluginTag.
	 */
	public function getPluginDependencysJoinPlugin($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PluginTagPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPluginDependencys === null) {
			if ($this->isNew()) {
				$this->collPluginDependencys = array();
			} else {

				$criteria->add(PluginDependencyPeer::PLUGIN_TAG_ID, $this->id);

				$this->collPluginDependencys = PluginDependencyPeer::doSelectJoinPlugin($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PluginDependencyPeer::PLUGIN_TAG_ID, $this->id);

			if (!isset($this->lastPluginDependencyCriteria) || !$this->lastPluginDependencyCriteria->equals($criteria)) {
				$this->collPluginDependencys = PluginDependencyPeer::doSelectJoinPlugin($criteria, $con, $join_behavior);
			}
		}
		$this->lastPluginDependencyCriteria = $criteria;

		return $this->collPluginDependencys;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPlugins) {
				foreach ((array) $this->collPlugins as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPluginDependencys) {
				foreach ((array) $this->collPluginDependencys as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPlugins = null;
		$this->collPluginDependencys = null;
			$this->aPlugin = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasePluginTag:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasePluginTag::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasePluginTag
